# Generated by Django 6.0.7 on 2026-08-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_monthlyexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='monthly_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.monthlyexpense'),
        ),
    ]
