# Generated by Django 6.0.7 on 2026-08-12 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_monthlyexpense_owner_payment_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="is_active",
        ),
    ]
