# Generated by Django 6.0.7 on 2026-08-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_client_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.client",
            ),
        ),
    ]
