from django.urls import include, path

from finance.views import (
    client_add_view,
    client_create_ajax_view,
    client_delete_view,
    client_detail_view,
    client_search_view,
    clients_view,
    monthly_expense_add_view,
    monthly_expense_delete_view,
    monthly_expense_edit_view,
    monthly_expenses_view,
    payment_add_view,
    payment_delete_view,
    payment_edit_view,
    payment_service_add_view,
    payment_service_delete_view,
    payment_service_edit_view,
    payment_services_view,
    payments_view,
    statistics_view,
)

urlpatterns = [
    path("", statistics_view, name="statistics"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("payments/", payments_view, name="payments"),
    path("payments/add/", payment_add_view, name="payment-add"),
    path("payments/<int:pk>/edit/", payment_edit_view, name="payment-edit"),
    path("payments/<int:pk>/delete/", payment_delete_view, name="payment-delete"),
    path("payment-clients/search/", client_search_view, name="payment-client-search"),
    path(
        "payment-clients/create/",
        client_create_ajax_view,
        name="payment-client-create",
    ),
    path("payment-services/", payment_services_view, name="payment-services"),
    path("payment-services/add/", payment_service_add_view, name="payment-service-add"),
    path(
        "payment-services/<int:pk>/edit/",
        payment_service_edit_view,
        name="payment-service-edit",
    ),
    path(
        "payment-services/<int:pk>/delete/",
        payment_service_delete_view,
        name="payment-service-delete",
    ),
    path("monthly-expenses/", monthly_expenses_view, name="monthly-expenses"),
    path("monthly-expenses/add/", monthly_expense_add_view, name="monthly-expense-add"),
    path(
        "monthly-expenses/<int:pk>/edit/",
        monthly_expense_edit_view,
        name="monthly-expense-edit",
    ),
    path(
        "monthly-expenses/<int:pk>/delete/",
        monthly_expense_delete_view,
        name="monthly-expense-delete",
    ),
    path("clients/", clients_view, name="clients"),
    path("clients/<int:pk>/", client_detail_view, name="client-detail"),
    path("clients/add/", client_add_view, name="client-add"),
    path("clients/<int:pk>/delete/", client_delete_view, name="client-delete"),
]
